# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-02 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseType', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('structure', models.CharField(max_length=50)),
                ('inArea', models.CharField(max_length=50)),
                ('buildType', models.CharField(max_length=50)),
                ('buildHead', models.CharField(max_length=20)),
                ('buildStruct', models.CharField(max_length=20)),
                ('decorate', models.CharField(max_length=20)),
                ('ladderHouPro', models.CharField(max_length=20)),
                ('heatMethod', models.CharField(max_length=10)),
                ('lift', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('address_wu', models.CharField(max_length=200)),
                ('address_qu', models.CharField(max_length=200)),
                ('address_detail', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '房屋基本属性信息',
                'db_table': 'tb_baseattr',
                'verbose_name': '房屋基本属性信息',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': '房屋筛选总表',
                'db_table': 'tb_container',
                'verbose_name': '房屋筛选总表',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('vide', models.CharField(max_length=100)),
                ('focus', models.IntegerField()),
                ('source', models.CharField(max_length=20)),
                ('area', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('Container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='info.Container')),
                ('baseAttr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='info.BaseAttr')),
            ],
            options={
                'verbose_name_plural': '房屋信息',
                'db_table': 'tb_house',
                'verbose_name': '房屋信息',
            },
        ),
        migrations.CreateModel(
            name='HouseCharact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': '房屋特色',
                'db_table': 'tb_housecharact',
                'verbose_name': '房屋特色',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='暂无数据', max_length=200)),
                ('url', models.CharField(default='https://s1.ljcdn.com/pegasus/redskull/images/common/blank.gif?_v=201904181525136', max_length=200)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='info.House')),
            ],
            options={
                'verbose_name_plural': '房屋图片',
                'db_table': 'tb_image',
                'verbose_name': '房屋图片',
            },
        ),
        migrations.CreateModel(
            name='SelecttData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_wu', models.CharField(max_length=200)),
                ('address_qu', models.CharField(max_length=200)),
                ('address_detail', models.CharField(max_length=200)),
                ('vides', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('houseType', models.CharField(max_length=200, null=True)),
                ('area', models.CharField(max_length=200)),
                ('tagList', models.CharField(max_length=200)),
                ('houseHead', models.CharField(max_length=200, null=True)),
                ('floor', models.CharField(max_length=200, null=True)),
                ('buildYear', models.CharField(max_length=200, null=True)),
                ('decorate', models.CharField(max_length=200, null=True)),
                ('houseUse', models.CharField(max_length=200, null=True)),
                ('lift', models.CharField(max_length=200, null=True)),
                ('heatMethod', models.CharField(max_length=200, null=True)),
                ('tradeOwnership', models.CharField(max_length=200, null=True)),
                ('buildType', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '房屋筛选表',
                'db_table': 'tb_selectData',
                'verbose_name': '房屋筛选表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '房屋标签',
                'db_table': 'tb_tag',
                'verbose_name': '房屋标签',
            },
        ),
        migrations.CreateModel(
            name='TradeAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listedTime', models.CharField(max_length=50)),
                ('tradeOwershid', models.CharField(max_length=50)),
                ('lastTransationTime', models.CharField(max_length=50)),
                ('house_use', models.CharField(max_length=50)),
                ('house_year', models.CharField(max_length=20)),
                ('belongTo', models.CharField(max_length=20)),
                ('mortgageInfo', models.CharField(max_length=200)),
                ('roomBak', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '房屋基本属性信息',
                'db_table': 'tb_tradeattr',
                'verbose_name': '房屋基本属性信息',
            },
        ),
        migrations.AddField(
            model_name='housecharact',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housecharact', to='info.Tag'),
        ),
        migrations.AddField(
            model_name='housecharact',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housecharact', to='info.House'),
        ),
        migrations.AddField(
            model_name='house',
            name='selectData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='info.SelecttData'),
        ),
        migrations.AddField(
            model_name='house',
            name='tradeAttr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='info.TradeAttr'),
        ),
    ]
